[package]
name = "fuzzy-octo-rotary-phone"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git" }
bevy_rand = { version = "0.11.0", features=["rand_chacha", "wyrand"]}

